version: '3.3'

services:
  app:
    container_name: "app"
    build: ./
    volumes:
      - .:/usr/src
    working_dir: "/usr/src"
    ports: 
      - 5000:5000
    depends_on:
      - db
    command: ['npm', 'run', 'start']
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432